# Generated by Django 3.2.25 on 2024-06-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='reviews',
        ),
    ]
