# Generated by Django 3.2.25 on 2024-06-24 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0005_auto_20240614_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username_id',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='about_us.username'),
                                    ),]
