# Generated by Django 3.2.25 on 2024-06-25 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0008_auto_20240625_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username_id',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='about_us.username'),
                                    ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
