# Generated by Django 3.2.25 on 2024-05-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='art_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='art_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='artwork',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='product_num',
        ),
    ]
