# Generated by Django 3.2.25 on 2024-05-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240513_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
